services:
  cloudsaver:
    image: jiangrui1994/cloudsaver:latest
    container_name: cloud-saver
    ports:
      - "8978:8008"
    environment:
      - USERNAME=注册码230713
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    restart: unless-stopped