#version: '3.9'

services:

 contra:

  container_name: contra

  image: swr.cn-north-4.myhuaweicloud.com/firfe/contra:2025.05.09

  network_mode: bridge

  restart: always

  logging:

   options:

    max-size: 1m

    max-file: '3'

  ports:

   - 4499:3000