services:
  ddns-go:
    image: jeessy/ddns-go:latest
    container_name: ddns-go
    restart: unless-stopped
    ports:
      - "4044:9876"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/root