services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./media:/data/media
      - /dev/dri:/dev/dri
    ports:
      - 4077:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped