services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - /appdata/emby/config:/config
      - /media/movies:/data/movies
      - /dev/dri:/dev/dri
    ports:
      - 4077:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      - media_network
    depends_on:
      - moviepilot

networks:
  media_network:
    external: true
    name: media_network