version: '3.8'

services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./movies:/data/movies
      - /dev/dri:/dev/dri
    ports:
      - 4077:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      media_network:
        aliases:
          - emby

networks:
  media_network:
    external: true
    name: media_network