services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    volumes:
      - ./config:/config
      - ./movies:/data/movies
      - /dev/dri:/dev/dri
    ports:
      - 4077:8096
      - 8920:8920
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
    networks:
      media_network:
        aliases:
          - emby

networks:
  media_network:
    driver: bridge
    name: media_network