services:
  firefox:
    image: jlesage/firefox:latest
    container_name: firefox
    ports:
      - 27580:5800
    volumes:
      - ./config:/config:rw
      - ./fonts:/usr/share/fonts
      - ./Downloads:/config/downloads
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge