services:
  godoos:
    image: godoos/godoos:latest
    container_name: godoos
    ports:
      - 26088:56780
    volumes:
      - ./godoos:/root/.godoos/os
    environment:
      - TZ=Asia/Shanghai
    restart: always
    network_mode: bridge