version: '3.8'

networks:
  homepage-network:
    driver: bridge

services:
  homepage-config-manager:
    image: kwangyeonc/homepage-config-manager:latest
    container_name: homepage-config-manager 
    user: "0:0"
    ports:
      - "3033:3001"  # 配置页面端口
    environment:
      - NODE_ENV=production
      - ACCESS_PASSWORD=123321  # 设置登录密码
      - CONFIG_PATH=/app/config
    volumes:
      - ./config:/app/config       
      - /var/run/docker.sock:/var/run/docker.sock:ro          
    networks:
      - homepage-network
    depends_on:
      - homepage
    restart: unless-stopped

  homepage:
    image: ghcr.nju.edu.cn/gethomepage/homepage:latest
    container_name: homepage
    user: "0:0"  # 修正：从environment移动到正确位置
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=ip:3080  # 修正：使用正确的环境变量语法
    ports:
      - "3034:3000"  # 导航页端口
    volumes:
      - ./config:/app/config           
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - homepage-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]  # 修正：添加端口号
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"  
      - "61209:61209"  
    volumes:
      - /:/rootfs:ro  
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GLANCES_OPT=-w  
    networks:  # 新增：添加glances到同一网络
      - homepage-network
    deploy:
      resources:
        limits:
          memory: 128M