name: paint-board
services:
  paint-board:
    container_name: paint-board
    image: swr.cn-north-4.myhuaweicloud.com/firfe/paint-board:2.0.0
    network_mode: bridge
    restart: always
    logging:
      options:
        max-size: 1m
        max-file: '1'
    ports:
      - 5139:5139