services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=4096
      - USERNAME=admin
      - PASSWORD=admin123
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    ports:
      - 4096:4096
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    name: media_network
    external: true