services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=4096  # 修改为4096
      - USERNAME=admin
      - PASSWORD=admin123
    volumes:
      - /appdata/qbittorrent/config:/config
      - /media/downloads:/downloads
    ports:
      - 4096:4096  # 修改为4096
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - media_network

networks:
  media_network:
    external: true
    name: media_network