services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - UMASK_SET=022
      - WEBUI_PORT=8081 
      - USERNAME=admin
      - PASSWORD=进入容器日志查看初始密码
    volumes:
      - ./config:/config # 绝对路径请修改为自己的config文件夹
      - ./downloads:/downloads # 绝对路径请修改为自己的downloads文件夹
    ports:
      - 6881:6881 
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped