services:
  reader:
    image: hectorqin/reader
    container_name: reader
    restart: always
    ports:
      - "4396:8080"
    networks:
      - share_net
    volumes:
      - ./logs:/logs
      - ./storage:/storage
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - READER_APP_USERLIMIT=50
      - READER_APP_USERBOOKLIMIT=200
      - READER_APP_CACHECHAPTERCONTENT=true
      - READER_APP_SECURE=true
      - READER_APP_SECUREKEY=admin
      - READER_APP_INVITECODE=admin123

networks:
  share_net:
    driver: bridge