services:
  mind-map:
    image: hraulein/mind-map:latest
    container_name: mind-map
    restart: always
    ports:
      - "7653:8080"  # 访问地址为 http://<你的服务器IP>:8080
    environment:
      - GIN_MODE=release