services:
  main:
    image: b3log/siyuan
    container_name: siyuan
    ports:
      - "6106:6806"
    volumes:
      - ./siyuan:/siyuan/workspace
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
     - PASSWORD=admin123
    command:
      - --workspace=/siyuan/workspace/
      - --accessAuthCode=admin123
    restart: unless-stopped