services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - UMASK_SET=022
    # Sonarr 默认无认证，认证在Web界面设置
    # 首次登录后，在 Settings -> General -> Authentication 中启用
    volumes:
      - ./config:/config
      - ./tv:/tv
      - ./downloads:/downloads
    ports:
      - "4890:8989"
    restart: unless-stopped
    networks:
      - sonarr-network

networks:
  sonarr-network:
    driver: bridge